name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: |
          npm run build || { echo "Build failed"; exit 1; }

      # Check and upload the dist directory as an artifact
      - name: Upload dist folder as an artifact
        run: |
          if [ -d "dist" ]; then
            echo "Uploading dist directory..."
            tar -czf dist.tar.gz dist
            echo "::set-output name=BUILD_DIR::dist"
          else
            echo "Dist directory does not exist."
            exit 1
          fi
        continue-on-error: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Download and extract the artifact from the previous job
      - name: Download and extract the dist artifact
        run: |
          tar -xzf dist.tar.gz

      # Deploy the extracted dist folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          build-folder: dist
